# Define el servicio de backend
[[service]]
name = "backend-service"
# Le dice a Railway que busque los archivos de configuración (como package.json) dentro de la carpeta 'backend'
path = "backend" 

# Define los comandos a ejecutar (Build y Start)
[service.build]
# Esto se ejecutaría dentro de la carpeta 'backend'
build_command = "npm install" 

[service.deploy]
# Este comando de inicio se ejecutará DESPUÉS de haber ejecutado el build y si existe en el package.json
start_command = "npm start"

